version: "3"

services:
  app:
    container_name: gh_archive_analysis
    image: gh_archive_analysis:latest
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - .:/app